#zuul.routes.backoffice.path: /api/persons/**
#zuul.routes.backoffice.url: http://localhost:9000/

zuul.routes.token.path: /api/auth/**
zuul.routes.token.url: http://localhost:8082/

ribbon.eureka.enabled: false

spring.application.name: api-gateway
server.port: 8080
